//GEN-BEGIN:autogenerated
// DO NOT MODIFY THIS FILE.  IT HAS BEEN AUTOMATICALLY GENERATED
// CHANGES MAY BE OVERWRITTEN WITHOUT NOTICE
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.codename1.testws;



/**
 *
 * @author shannah
 */

public class TestVersionedClass {
    int a;
    int b;
    String name;
    
    class Version1 {
        int a;
        int b;
        
    }
    
    class Version2 {
        int a;
        int b;
        String name;
        float aMistake;
    }
}

//GEN-END:autogenerated
